import 'package:store_manager/models/order.dart';

Order buildSampleOrder() {
  return Order(
    id: 1001,
    parentId: 0,
    status: 'processing',
    currency: 'VND',
    version: '1.0',
    pricesIncludeTax: false,
    dateCreated: DateTime.now().subtract(const Duration(days: 1)),
    dateModified: DateTime.now(),
    discountTotal: '10000',
    discountTax: '0',
    shippingTotal: '15000',
    shippingTax: '0',
    cartTax: '10000',
    total: '215000',
    totalTax: '10000',
    customerId: 88,
    orderKey: 'WC-1001',
    billing: Billing(
      firstName: 'Nguyen',
      lastName: 'An',
      company: 'ABC Co.,Ltd',
      address1: '123 Nguyen Trai',
      address2: 'P.7',
      city: 'HCM',
      state: 'Q.5',
      postcode: '700000',
      country: 'Vietnam',
      email: 'an.nguyen@example.com',
      phone: '0909123456',
    ),
    shipping: Shipping(
      firstName: 'Nguyen',
      lastName: 'An',
      company: 'ABC Co.,Ltd',
      address1: '456 Le Loi',
      address2: '',
      city: 'HCM',
      state: 'Q.1',
      postcode: '700000',
      country: 'Vietnam',
      phone: '0909123456',
    ),
    paymentMethod: 'cod',
    paymentMethodTitle: 'Thanh toán khi nhận hàng',
    transactionId: 'TXN-123456',
    customerIpAddress: '127.0.0.1',
    customerUserAgent: 'Dart/Flutter',
    createdVia: 'app',
    customerNote: 'Giao giờ hành chính',
    dateCompleted: null,
    datePaid: DateTime.now(),
    cartHash: 'hash123',
    number: '1001',
    metaData: const [],
    lineItems: [
      OrderItem(
        id: 1,
        name: 'Áo thun cổ tròn',
        productId: 11,
        variationId: 0,
        quantity: 2,
        taxClass: '',
        subtotal: '200000',
        subtotalTax: '10000',
        total: '210000',
        totalTax: '10000',
        sku: 'TS-01',
        price: 105000,
        image: null,
        metaData: const [],
      ),
      OrderItem(
        id: 2,
        name: 'Quần jeans xanh',
        productId: 22,
        variationId: 0,
        quantity: 1,
        taxClass: '',
        subtotal: '100000',
        subtotalTax: '0',
        total: '100000',
        totalTax: '0',
        sku: 'J-01',
        price: 100000,
        image: null,
        metaData: const [],
      ),
    ],
    currencySymbol: '₫',
  );
}


